package file;

import java.io.*;
import java.util.ArrayList;

import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.parser.PdfTextExtractor;

public class FReader {
	FileInputStream fin;
	BufferedReader br;
	
	public FReader() {}
	public FReader(String filename) throws FileNotFoundException {
		fin = new FileInputStream(filename);
		br  = new BufferedReader(new InputStreamReader(fin));
	}
	
	public String readLine() throws IOException {
		return br.readLine();
	}
	
	public ArrayList<String> readPDFFile(String filename, boolean remove_whitespace) throws IOException {
		ArrayList<String> result = new ArrayList<String>();
		PdfReader reader         = new PdfReader(filename);
		String content           = "";
		
		int n_pages = reader.getNumberOfPages();
		// extract all page content
		for (int n = 1; n <= n_pages; n++) {
			//if (n != 8) continue;
			String tmp = PdfTextExtractor.getTextFromPage(reader, n) + System.getProperty("line.separator");
			if (remove_whitespace) tmp = tmp.replaceAll(" ", "").replaceAll("(-)([^\\d\\w]|\\S)", "-");
			tmp = tmp.replaceAll("\\[QuotedÊtextÊhidden\\]", "");
			tmp = tmp.replaceAll("\\-\\-", "");
			// remove all useless whitespace generated by PdfReader
			content += tmp;
			//content += new String(tmp.getBytes("UTF-8"), "UTF-8");
		}
		for (String sentence : content.split("\\n")) {
			//System.out.println(sentence.length() + " --> " + sentence);
			if (sentence.length() >= 2) result.add(sentence);
		}
		return result;

	}
	
	public void close() throws IOException {
		fin.close();
		br.close();
	}
}
